"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
LEGACY_ROOT = BASE_DIR.parent

# Load project .env for Gunicorn / manage.py / Supervisor (no-op if missing).
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-9di%qhb=c(m1l92w*g=l8uwjdzwe1wj0you=4i=o=f)n(zomjn",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "1") == "1"

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        "DJANGO_ALLOWED_HOSTS",
        "localhost,127.0.0.1,testserver,52.15.199.202,3.138.112.5",
    ).split(",")
    if host.strip()
]


# Application definition

def _env_bool(name: str, default: bool = False) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.lower() in ("1", "true", "yes", "on")


# Production bare-metal: set DJANGO_USE_S3=1. Local dev leaves this unset (filesystem).
USE_S3_MEDIA = _env_bool("DJANGO_USE_S3")

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'archive.apps.ArchiveConfig',
]
if USE_S3_MEDIA:
    INSTALLED_APPS.append("storages")

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if os.environ.get("POSTGRES_DB"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("POSTGRES_DB"),
            "USER": os.environ.get("POSTGRES_USER", "postgres"),
            "PASSWORD": os.environ.get("POSTGRES_PASSWORD", ""),
            "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
            "PORT": os.environ.get("POSTGRES_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = os.environ.get("STATIC_URL", "/static/")
STATICFILES_DIRS = [BASE_DIR / "static"]
# STATICFILES_DIRS = [
#     LEGACY_ROOT / 'assets' / 'assets',
#     LEGACY_ROOT / 'images',
#     LEGACY_ROOT,
# ]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

_staticfiles_backend = (
    "whitenoise.storage.CompressedManifestStaticFilesStorage"
    if not DEBUG
    else "django.contrib.staticfiles.storage.StaticFilesStorage"
)

MEDIA_ROOT = BASE_DIR / "media"

if USE_S3_MEDIA:
    AWS_STORAGE_BUCKET_NAME = os.environ.get(
        "AWS_STORAGE_BUCKET_NAME", "rc-bucket-media"
    )
    AWS_S3_REGION_NAME = os.environ.get("AWS_S3_REGION_NAME", "us-east-2")
    AWS_S3_SIGNATURE_VERSION = "s3v4"
    # EC2 IAM role: leave AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY unset; boto3
    # uses the instance profile automatically. Set them only for local S3 testing.
    if os.environ.get("AWS_ACCESS_KEY_ID"):
        AWS_ACCESS_KEY_ID = os.environ["AWS_ACCESS_KEY_ID"]
    if os.environ.get("AWS_SECRET_ACCESS_KEY"):
        AWS_SECRET_ACCESS_KEY = os.environ["AWS_SECRET_ACCESS_KEY"]
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = False
    AWS_LOCATION = os.environ.get("AWS_LOCATION", "media")

    _default_media_url = (
        f"https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/"
        f"{AWS_LOCATION}/"
    )
    MEDIA_URL = os.environ.get("MEDIA_URL", _default_media_url)

    STORAGES = {
        "default": {"BACKEND": "storages.backends.s3.S3Storage"},
        "staticfiles": {"BACKEND": _staticfiles_backend},
    }
else:
    MEDIA_URL = os.environ.get("MEDIA_URL", "/media/")
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {"BACKEND": _staticfiles_backend},
    }

# Magazine PDF scans can be 100–400 MB. Django defaults to 2.5 MB which can
# reject admin uploads; Nginx defaults to 1 MB (see deploy/nginx.conf).
def _upload_limit_mb(env_name: str, default_mb: int) -> int:
    return int(os.environ.get(env_name, str(default_mb))) * 1024 * 1024


DATA_UPLOAD_MAX_MEMORY_SIZE = _upload_limit_mb("DATA_UPLOAD_MAX_MB", 4000)
FILE_UPLOAD_MAX_MEMORY_SIZE = _upload_limit_mb("FILE_UPLOAD_MAX_MB", 10)

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# URL of the FastAPI search service (set via env in prod, defaults to dev port)
SEARCH_SERVICE_URL = os.environ.get("SEARCH_SERVICE_URL", "http://127.0.0.1:8001")
# Keep short so a slow SQLite scan cannot hang Gunicorn workers on a small EC2.
SEARCH_SERVICE_TIMEOUT = float(os.environ.get("SEARCH_SERVICE_TIMEOUT", "3"))


# Production-only security toggles. When DEBUG=False we assume the site is
# served over HTTPS via the reverse proxy (Nginx + LE/Caddy/Cloudflare).
# While running over plain HTTP (e.g. by IP before TLS is set up), set the
# DJANGO_*_SECURE / DJANGO_SSL_REDIRECT / DJANGO_HSTS_SECONDS toggles to 0.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = _env_bool("DJANGO_SSL_REDIRECT", True)
    SESSION_COOKIE_SECURE = _env_bool("DJANGO_SESSION_COOKIE_SECURE", True)
    CSRF_COOKIE_SECURE = _env_bool("DJANGO_CSRF_COOKIE_SECURE", True)
    SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"

# Origins trusted for CSRF-protected POSTs (admin login, forms). Django 4+
# requires the request Origin to be listed here. Provide a comma-separated
# list including scheme, e.g. "http://77.112.22.131,https://rchistoricalsociety.org".
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]
