# Generated by Django 6.0.5 on 2026-06-02 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('competition_plus', 'Competition Plus'), ('rev_up', 'Rev-Up'), ('rc_model_cars', 'RC Model Cars'), ('xtreme_rc_cars', 'Xtreme RC Cars'), ('race_programs_rules', 'Race Programs and Rules'), ('catalogs', 'Catalogs'), ('manuals', 'Manuals')], max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('month', models.CharField(blank=True, max_length=30)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/%Y/')),
                ('pdf_file_path', models.CharField(blank=True, help_text='Legacy/external PDF path. Used when no file is uploaded.', max_length=500)),
                ('available', models.BooleanField(default=True)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('page_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'year', 'month', 'publication_name'],
            },
        ),
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('url', models.URLField()),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='HomepagePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('image', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('linked_page', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('role_type', models.CharField(choices=[('driver', 'Driver'), ('industry', 'Industry')], max_length=20)),
                ('bio_text', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['role_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PodcastEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('audio_file', models.FileField(blank=True, help_text='Main audio file (optional if you add audio parts below).', upload_to='podcast/')),
                ('audio_link', models.CharField(blank=True, help_text='Optional external listen URL (used when no uploaded audio).', max_length=500)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='IFMAREvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('class_name', models.CharField(max_length=100)),
                ('results_data', models.TextField()),
            ],
            options={
                'ordering': ['year', 'class_name'],
                'unique_together': {('year', 'class_name')},
            },
        ),
        migrations.CreateModel(
            name='PodcastEpisodeAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('label', models.CharField(blank=True, help_text='Optional label, e.g. "Part 2".', max_length=120)),
                ('audio_file', models.FileField(upload_to='podcast/')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_parts', to='archive.podcastepisode')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PDFPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='archive.document')),
            ],
            options={
                'ordering': ['document_id', 'page_number'],
                'indexes': [models.Index(fields=['document', 'page_number'], name='archive_pdf_documen_7ee8a2_idx')],
                'unique_together': {('document', 'page_number')},
            },
        ),
    ]
