# Generated by Django 6.0.4 on 2026-04-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('competition_plus', 'Competition Plus'), ('rev_up', 'Rev-Up'), ('rc_model_cars', 'RC Model Cars'), ('xtreme_rc_cars', 'Xtreme RC Cars'), ('race_programs_rules', 'Race Programs and Rules'), ('catalogs', 'Catalogs'), ('manuals', 'Manuals')], max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('month', models.CharField(blank=True, max_length=30)),
                ('pdf_file_path', models.CharField(max_length=500)),
                ('available', models.BooleanField(default=True)),
                ('brand', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['category', 'year', 'month', 'publication_name'],
            },
        ),
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('url', models.URLField()),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='HomepagePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('image', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('linked_page', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('role_type', models.CharField(choices=[('driver', 'Driver'), ('industry', 'Industry')], max_length=20)),
                ('bio_text', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['role_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PodcastEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('audio_link', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='IFMAREvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('class_name', models.CharField(max_length=100)),
                ('results_data', models.TextField()),
            ],
            options={
                'ordering': ['year', 'class_name'],
                'unique_together': {('year', 'class_name')},
            },
        ),
    ]
