# Generated by Django 6.0.5 on 2026-05-12 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='indexed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='page_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/%Y/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='pdf_file_path',
            field=models.CharField(blank=True, help_text='Legacy/external PDF path. Used when no file is uploaded.', max_length=500),
        ),
        migrations.CreateModel(
            name='PDFPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='archive.document')),
            ],
            options={
                'ordering': ['document_id', 'page_number'],
                'indexes': [models.Index(fields=['document', 'page_number'], name='archive_pdf_documen_7ee8a2_idx')],
                'unique_together': {('document', 'page_number')},
            },
        ),
    ]
